import os

ACNH_TWEET_DATA = os.getenv("ACNH_TWEET_DATA", None)
ACNH_NAMES_DATA = os.getenv("ACNH_NAMES_DATA", None)
ACNH_VILLAGER_DATA = os.getenv("ACNH_VILLAGER_DATA", None)
ACNH_CREATURE_DATA = os.getenv("ACNH_CREATURE_DATA", None)
ACNH_DB = os.getenv("ACNH_DB", None)
LEAVING, JOINING = 0, 1
NORTH, SOUTH = 0, 1